apiVersion: v1
# Using this example you can install helm mongodb chart and set the service type as LoadBalancer instaed default ClusterIp
# https://github.com/kubernetes/charts/blob/master/stable/mongodb/values.yaml
kind: context
owner: account
metadata:
  name: helm-mongo-values
spec:
  type: values
  data:
    serviceType: LoadBalancer
    
